Ev3UltraSonic:
  type: h4r_ev3_control/Ev3UltrasonicController
  max_range: 1.5
  min_range: 0.01
  frame_id: ultrasonic_link
  topic_name: /ultrasonic
  publish_rate: 10
  port: in1
  mode: distance
